### ISSUE TITLE
如何在HEXO中添加页面

### ISSUE THREAD

**Issue by rememberBr** [Sirice19/hexo-theme-Chic#1]
想问问  Categories，Tags，About这些页面怎么做的啊，还有怎么进一步的去加新的功能，没学过web有点懵逼啊

**Comment by Sirice19** [comment]
> 想问问 Categories，Tags，About这些页面怎么做的啊，还有怎么进一步的去加新的功能，没学过web有点懵逼啊

页面使用`hexo new page category/tag/about`命令生成。
新的功能需要你去学web，起码语言要能看得懂，使用框架时多看官方文档。
具体编写过程可以看我的这篇文章：[从零开始创建一个hexo主题 | Sirice's blog](https://sirice19.github.io/2019/06/02/Build-a-hexo-theme/)

另外 github作为开源社区，请尽量以标准格式提出issue，建议看下这篇文章[如何正确的提出一个 Issue ？ ](https://zhuanlan.zhihu.com/p/52370003)，比如你这个issue的标题可能不太利于后来有同样问题的人搜索，举个例子，不如改成“如何在hexo中添加页面？”这种。
大家都是萌新过来的，希望你保持热情，继续学习:smile:有问题可以继续交流哈~

**Comment by rememberBr** [comment]
非常感谢感谢大佬的帮助，下次一定注意
