### ISSUE TITLE
如何打造更具个性化的about页面，是否考虑加入搜索功能

### ISSUE THREAD

**Issue by rememberBr** [Sirice19/hexo-theme-Chic#2]
经过昨晚上的学习与摸索，已经成功的将tags与 Categories页面弄出来了，但是还有一些小的问题希望得到帮助。
1. about页面如何设置的更好看，我在百度上看到有人说直接在about/index.md里面编辑然后hexo会渲染出来，请问是否还有其他的方式，或者有什么好的建议。
2. 请问后期是否会加入搜索功能，本来想自己尝试添加的但是对web前端相关的知识完全小白担心弄不好。
3. 非常赞成作者对于博客应该有个封面的看法，这可能也是我一眼相中这款主题的原因，希望继续加油。

**Comment by Sirice19** [comment]
首先对这次的提问格式表扬一下，一看就是补过课了，问题明确理由清晰 :thumbsup:
回答下几个问题

1. about页面简单的可以直接编辑about/index.md,hexo这里会将index.md的内容当成一个文章内容来解析。这种方式好处就是简单，便于编辑。不好的地方就是这个页面受markdown语言的局限性限制。<br>
但是hexo这里还有些其他方式来编辑markdown，比如官方文档的[标签插件(Tag Plugins)](https://hexo.io/zh-cn/docs/tag-plugins),这个东西可以直接插入markdown文件中，相当于拓展hexo中markdown的语法。另外不要忘记，markdown本身就是支持HTML标签的,你可以直接按html的方式编辑about页面。<br>
如果你还是觉得markdown非常限制你的发挥，这时候如果你有web基础，你可以直接自己制作about页面，在themes\Chic\layout中添加一个about.ejs文件，以页面模板形式设计该页面，样式表写在themes\Chic\source\css中，最后在about/index.md中添加`layout: about`字段即可（同理于category页面形式）<br>
当你能做到这一步，那么你就离自己独立制作一个hexo主题不远了。<del>（其实你实在不会的话也可以扒别人的站嘛！）</del>

2. 是否加入搜索功能，从我之前使用hexo的体验来看，我个人觉得有了tag和category分类就已经很详细了，使用搜索的频率并不大……好像也没有什么需要特意搜索。秉承设计中“少就是多”的原则我暂时不会加入搜索和评论功能，但如果后来提这个需求的人比较多的话会考虑加入。

3. 没错哒！没有封面的主题简直就是没有灵魂好嘛！（愉快的达成共识.jpg:sunglasses:

**Comment by rememberBr** [comment]
非常感谢，我再去摸索一番😎
